# Generated by Django 2.1.2 on 2018-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
