# Generated by Django 2.1.2 on 2018-11-22 22:43

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_featured_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_images',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, form_size=None, size=None),
        ),
    ]
