# Generated by Django 2.1.2 on 2018-11-23 11:09

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20181123_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_txt_1',
            field=models.CharField(default='Insert a short description of yourself here', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_txt_2',
            field=models.CharField(default='Insert more about yourself here e.g work experiences', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='skillset',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, form_size=None, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='software_and_mediums',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, form_size=None, size=None),
        ),
    ]
