# Generated by Django 2.1.2 on 2018-11-08 15:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('ext', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('uploader_id', models.IntegerField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField()),
                ('uploader_id', models.IntegerField()),
            ],
        ),
    ]
