# Generated by Django 2.1.2 on 2018-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'uploader_id')},
        ),
    ]
