# Generated by Django 2.1.2 on 2018-10-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_auto_20181014_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
