# Generated by Django 2.1.2 on 2018-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_auto_20181015_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ext',
            field=models.CharField(default='.jpg', max_length=5),
            preserve_default=False,
        ),
    ]
