# Generated by Django 2.1.2 on 2018-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_image_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploader_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='uploader_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
